openapi: 3.0.1
info:
  version: 1.0.0
  title: Lambda Notes API Documentation
tags:
  - name: attachments
    description: Manage links to uploaded attachments
  - name: comments
    description: Create and manage comments within tasks
  - name: projects
    description: Create and manage projects
  - name: subtasks
    description: Create and manage subtasks for checklists in tasks
  - name: tags
    description: Create and manage tags within projects
  - name: tasks
    description: Create and manage tasks within projects
  - name: users
    description: Create and manage users and user settings. Handle user sessions.
paths:
  /api/projects:
    post:
      tags:
        - projects
      summary: Create a new project
      operationId: createProject
      requestBody:
        description: New project object
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schemas/Project'
      responses:
        '201':
          description: Successfully created new project
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    format: objectId
                  title:
                    type: string
                  description:
                    type: string
                example:
                  _id: 5b33c45d8d8bf66d4d44f1ec
                  title: Example Project 1
                  description: An example description.
        '400':
          $ref: '#components/responses/400BadRequest'
        '500':
          $ref: '#components/responses/500InternalServerError'
    get:
      tags:
        - projects
      summary: Get all existing projects
      operationId: getAllProjects
      responses:
        '200':
          description: Successfully returned array of projects
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      format: objectId
                    title:
                      type: string
                    members:
                      type: array
                      items:
                        type: object
                        properties:
                          _id:
                            type: string
                            format: objectId
                          firstName:
                            type: string
                          lastName:
                            type: string
                example:
                  - _id: 5b31ea59d62eb33eb93014e7
                    title: Example Project 1
                    members:
                    - _id: 5b31ce106d04832fd1e51f59
                      firstName: John
                      lastName: Smith
                    - _id: 5b31ce106d04832fd1e51f71
                      firstName: Jane
                      lastName: Smith
        '500':
          $ref: '#components/responses/500InternalServerError'
  /api/projects/{projectId}:
    get:
      tags:
        - projects
      summary: Get project by id
      operationId: getProjectById
      parameters:
        - $ref: '#/components/parameters/projectId'
      responses:
        '200':
          description: Successfully returned project
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  members:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                          format: objectId
                        firstName:
                          type: string
                        lastName:
                          type: string
                example:
                  _id: 5b33c45d8d8bf66d4d44f1ec
                  title: Example Project 2
                  description: An example project description.
                  members:
                  - _id: 5b31ce106d04832fd1e51f59
                    firstName: John
                    lastName: Smith
        '404':
          $ref: '#components/responses/404NotFound'
        '500':
          $ref: '#components/responses/500InternalServerError'
    put:
      tags:
        - projects
      summary: Update an existing project. Replaces entire object.
      operationId: updateProject
      requestBody:
        description: Updated project object
        required: 'true'
        content:
          application/json:
            schema:
              $ref: '#components/schemas/Project'
      parameters:
        - $ref: '#/components/parameters/projectId'
      responses:
        '200':
          description: Successfully updated project
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  members:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                          format: objectId
                        firstName:
                          type: string
                        lastName:
                          type: string
                example:
                  _id: 5b33c45d8d8bf66d4d44f1ec
                  title: Example Project 2
                  description: An example project description.
                  members:
                  - _id: 5b31ce106d04832fd1e51f59
                    firstName: John
                    lastName: Smith
        '400':
          $ref: '#components/responses/400BadRequest'
        '404':
          $ref: '#components/responses/404NotFound'
        '500':
          $ref: '#components/responses/500InternalServerError'
    delete:
      tags:
        - projects
      summary: Delete a project
      operationId: deleteProject
      parameters:
        - $ref: '#/components/parameters/projectId'
      responses:
        '200':
          description: Successfully deleted project
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                example:
                  _id: 5b31ea59d62eb33eb93014e7
        '404':
          $ref: '#components/responses/404NotFound'
        '500':
          $ref: '#components/responses/500InternalServerError'
  /api/projects/{projectId}/tags:
    get:
      tags:
        - projects
      summary: Get tags by project id
      operationId: getTagsByProjectId
      parameters:
        - $ref: '#/components/parameters/projectId'
      responses:
        '200':
          description: Successfully returned array of tags for specified project
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Tag'
        '404':
          $ref: '#components/responses/404NotFound'
        '500':
          $ref: '#components/responses/500InternalServerError'
  /api/tags:
    post:
      tags:
        - tags
      summary: Create a new tag
      operationId: createTag
      requestBody:
        description: New tag object
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schemas/Tag'
      responses:
        '201':
          description: Successfully created new project
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Tag'
        '400':
          $ref: '#components/responses/400BadRequest'
        '500':
          $ref: '#components/responses/500InternalServerError'
  /api/tags/{tagId}:
    put:
      tags:
        - tags
      summary: Update an existing tag. Replaces entire object.
      operationId: updateTag
      requestBody:
        description: Updated tag object
        required: 'true'
        content:
          application/json:
            schema:
              $ref: '#components/schemas/Tag'
      parameters:
        - $ref: '#/components/parameters/tagId'
      responses:
        '200':
          description: Successfully updated tag
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Tag'
        '400':
          $ref: '#components/responses/400BadRequest'
        '404':
          $ref: '#components/responses/404NotFound'
        '500':
          $ref: '#components/responses/500InternalServerError'
    delete:
      tags:
      - tags
      summary: Delete a tag
      operationId: deleteTag
      parameters:
        - $ref: '#/components/parameters/tagId'
      responses:
        '200':
          description: Successfully deleted tag
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                example:
                  _id: 5b34370580f5b90ff8494ac4
        '404':
          $ref: '#components/responses/404NotFound'
        '500':
          $ref: '#components/responses/500InternalServerError'
  /api/tasks:
    post:
      tags:
        - tasks
      summary: Create a new task
      operationId: createTask
      requestBody:
        description: New task object
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schemas/Task'
      responses:
        '201':
          description: Successfully created new task
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Task'
        '400':
          $ref: '#components/responses/400BadRequest'
        '500':
          $ref: '#components/responses/500InternalServerError'
    get:
      tags:
        - tasks
      summary: Get all existing tasks
      operationId: getAllTasks
      responses:
        '200':
          description: Successfully returned array of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Task'
        '500':
          $ref: '#components/responses/500InternalServerError'
  /api/tasks/{taskId}:
    get:
      tags:
        - tasks
      summary: Get task by id
      operationId: getTaskById
      parameters:
        - $ref: '#/components/parameters/taskId'
      responses:
        '200':
          description: Successfully returned task
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Task'
        '404':
          $ref: '#components/responses/404NotFound'
        '500':
          $ref: '#components/responses/500InternalServerError'
    put:
      tags:
        - tasks
      summary: Update an existing task. Replaces entire object.
      operationId: updateTask
      requestBody:
        description: New task object
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schemas/Task'
      parameters:
        - $ref: '#/components/parameters/taskId'
      responses:
        '200':
          description: Successfully updated task
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Task'
        '400':
          $ref: '#components/responses/400BadRequest'
        '404':
          $ref: '#components/responses/404NotFound'
        '500':
          $ref: '#components/responses/500InternalServerError'
    delete:
      tags:
        - tasks
      summary: Delete a task
      operationId: deleteTask
      parameters:
        - $ref: '#/components/parameters/taskId'
      responses:
        '200':
          description: Successfully deleted task
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                example:
                  _id: 5b33e2dfc55019773e08217d
        '404':
          $ref: '#components/responses/404NotFound'
        '500':
          $ref: '#components/responses/500InternalServerError'
  /api/users:
    post:
      tags:
      - users
      summary: Create a new user
      operationId: createUser
      requestBody:
        description: New user object
        required: 'true'
        content:
          application/json:
            schema:
              $ref: '#components/schemas/User'
      responses:
        '201':
          description: Successfully created new user
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  firstName:
                    type: string
                  lastName:
                    type: string
                  email:
                    type: string
                example:
                  _id: 5b31ce106d04832fd1e51f59
                  firstName: John
                  lastName: Smith
                  email: johnSmith@example.com
        '400':
          $ref: '#components/responses/400BadRequest'
        '500':
          $ref: '#components/responses/500InternalServerError'
    get:
      tags:
      - users
      summary: Get all existing users
      operationId: getAllUsers
      responses:
        '200':
          description: Successfully returned array of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    firstName:
                      type: string
                    lastName:
                      type: string
                    email:
                      type: string
                example:
                - _id: 5b31ce106d04832fd1e51f59
                  firstName: John
                  lastName: Smith
                  email: johnSmith@example.com
                - _id: 5b31ce106d04832fd1e51f71
                  firstName: Jane
                  lastName: Smith
                  email: janeSmith@example.com
        '500':
          $ref: '#components/responses/500InternalServerError'
  /api/users/{userId}:
    get:
      tags:
      - users
      summary: Get user by id
      operationId: getUserById
      parameters:
        - $ref: '#/components/parameters/userId'
      responses:
        '200':
          description: Successfully returned user
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  firstName:
                    type: string
                  lastName:
                    type: string
                  email:
                    type: string
                example:
                  _id: 5b31ce106d04832fd1e51f59
                  firstName: John
                  lastName: Smith
                  email: johnSmith@example.com
        '404':
          $ref: '#components/responses/404NotFound'
        '500':
          $ref: '#components/responses/500InternalServerError'
    put:
      tags:
      - users
      summary: Update an existing user. Replaces entire object.
      operationId: updateUser
      requestBody:
        description: Updated user object
        required: 'true'
        content:
          application/json:
            schema:
              $ref: '#components/schemas/User'
      parameters:
        - $ref: '#/components/parameters/userId'
      responses:
        '200':
          description: Successfully updated user
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  firstName:
                    type: string
                  lastName:
                    type: string
                  email:
                    type: string
                example:
                  _id: 5b31ce106d04832fd1e51f59
                  firstName: John
                  lastName: Smith
                  email: johnSmith@example.com
        '400':
          $ref: '#components/responses/400BadRequest'
        '404':
          $ref: '#components/responses/404NotFound'
        '500':
          $ref: '#components/responses/500InternalServerError'
    delete:
      tags:
      - users
      summary: Deletes a user
      operationId: deleteUser
      parameters:
        - $ref: '#/components/parameters/userId'
      responses:
        '200':
          description: Successfully deleted user
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                example:
                  _id: 5b31ce106d04832fd1e51f59
        '404':
          $ref: '#components/responses/404NotFound'
        '500':
          $ref: '#components/responses/500InternalServerError'
components:
  #-------------------------------
  # Reusable schemas (data models)
  #-------------------------------
  schemas:
    Attachment:
      title: Attachment
      required:
        - name
        - link
      properties:
        name:
          description: Name of attached file
          type: string
          example: home-page-mockup.pdf
        link:
          description: Cloud storage link for saved file
          type: string
          example: https://example.s3.amazonaws.com/attachment.pdf
    Comment:
      title: Comment
      required:
        - comment
        - author
        - date
      properties:
        comment:
          description: Comment body
          type: string
          example: An example comment.
        author:
          description: User id of person who wrote the comment
          type: string
          format: objectId
          example: 5b1ed13e8cea93c6ba72b1da
        date:
          description: Date the comment was posted
          type: string
          format: date
          example: 06/27/2018
    Project:
      title: Project
      required:
        - title
        - members
      properties:
        title:
          description: Descriptive title for project
          type: string
          example: Example Project 1
        description:
          description: Additional details regarding project
          type: string
          example: An example description.
        members:
          description: Array of user id's assigned to project
          type: array
          items:
            type: string
            format: objectId
          example: ['5b1ed13e8cea93c6ba72b1da', '5b1ed13e8cea93c6ba72b1db', '5b1ed13e8cea93c6ba72b1dc']
    Subtask:
      title: Subtask
      required:
        - description
        - completed
      properties:
        description:
          description: A description of the subtask
          type: string
          example: An example description.
        completed:
          description: Subtasks' completed status
          type: boolean
          default: false
          example: false
    Tag:
      title: Tag
      required:
        - project
        - description
        - color
      properties:
        project:
          description: Id of existing project that tag belongs to
          type: string
          format: objectId
          example: 5b1ed13e8cea93c6ba72b1da
        description:
          description: Descriptive title for tag
          type: string
          example: High Priority
        color:
          description: "Background color for tag. Allowed values: black, white, blue, green, red, yellow, purple"
          type: string
          example: red
    Task:
      title: Task
      required:
        - project
        - title
      properties:
        project:
          description: Id of existing project that task belongs to
          type: string
          format: objectId
          example: 5b1ed13e8cea93c6ba72b1da
        title:
          description: Descriptive title for task
          type: string
          example: An example task title
        description:
          description: Additional details regarding task
          type: string
          example: An example task description.
        assignee:
          description: Array of user id's assigned to task
          type: array
          items:
            type: string
            format: objectId
          example: ['5b1ed13e8cea93c6ba72b1da']
        dueDate:
          description: Date the task is due
          type: string
          format: date
          example: 06/24/2018
        tags:
          description: Array of tag id's belonging to task
          type: array
          items:
            type: string
            format: objectId
          example: ['5b1ed13e8cea93c6ba72b1da', '5b1ed13e8cea93c6ba72b1db', '5b1ed13e8cea93c6ba72b1dc']
        completed:
          description: Task's completed status
          type: Boolean
          example: false
          default: false
        comments:
          description: Array of comment id's belonging to task
          type: array
          items:
            type: string
            format: objectId
          example: ['5b1ed13e8cea93c6ba72b1da', '5b1ed13e8cea93c6ba72b1db', '5b1ed13e8cea93c6ba72b1dc']
        attachments:
          description: Array of attachment id's belonging to task
          type: array
          items:
            type: string
            format: objectId
          example: ['5b1ed13e8cea93c6ba72b1da', '5b1ed13e8cea93c6ba72b1db', '5b1ed13e8cea93c6ba72b1dc']
    User:
      title: User
      required:
        - firstName
        - lastName
        - email
        - password
      properties:
        firstName:
          description: User's first name
          type: string
          example: John
        lastName:
          description: User's last name
          type: string
          example: Smith
        email:
          description: User's email address
          type: string
          format: email
          example: johnsmith@example.com
        password:
          description: "User's password containing 1 uppercase letter, 1 lowercase
            letter, 1 digit and 1 special character: !, @, #, $, %, &"
          type: string
          format: password
          minLength: 8
          example: Password@1
  #-------------------------------
  # Reusable operation parameters
  #-------------------------------
  parameters:
    projectId:
      name: projectId
      in: path
      description: The project id assigned by the database
      required: true
      schema:
        type: string
        format: objectId
      example: 5b33c45d8d8bf66d4d44f1ec
    tagId:
      name: tagId
      in: path
      description: The tag id assigned by the database
      required: true
      schema:
        type: string
        format: objectId
      example: 5b34370580f5b90ff8494ac4
    taskId:
      name: taskId
      in: path
      description: The task id assigned by the database
      required: true
      schema:
        type: string
        format: objectId
      example: 5b33e2dfc55019773e08217d
    userId:
      name: userId
      in: path
      description: The user id assigned by the database
      required: true
      schema:
        type: string
        format: objectId
      example: 5b31ce106d04832fd1e51f59
  #-------------------------------
  # Reusable responses
  #-------------------------------
  responses:
    400BadRequest:
      description: Bad request from validation error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
            example:
              error: 'Validation failed: {ADDITIONAL DETAILS}'
    404NotFound:
      description: Document not found. Id does not exist.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
            example:
              error: The document with the specified ID does not exist.
    500InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
            example:
              error: The action could not be completed.

